### ISSUE TITLE
Add a REE service that listen to client requests

### ISSUE THREAD

**Issue by neithanmo** [Zondax/hello-rustee#7]
This service runs on the Host and the protocol being used should be transparent to the application, giving room for further improvements even changing the protocol must not affect the host application.
It is possible at this stage of the development to use JSON-RPC over HTTP.

**Comment by becominginsane** [comment]
This is currently available to use and test under `remotee-signer` branch:

1. `REE/deps/host-common` contains the interface definition for all "host services" (connections to the outside world), see `REEService` trait

2. `REE/deps/jsonrpc/zkms` is the definition of the JSONRPC interface 
3. `REE/deps/jsonrpc/host` is the implementation of the JSONRPC interface and `REEService` 

4. `REE/lib/host` glues everything toghether:
1. starts the service found in `host-jsonrpc` crate
2. feeds the service & the handler (optee_handler module) to the `host-app` crate
